### ISSUE TITLE
2년차 개발자의 회고록입니다.

### ISSUE THREAD

**Issue by SambaLim** [oaksong/developers-retrospective#12]
https://sambalim.tistory.com/118
2019년 개발 2년차를 맞이한 회고록입니다😊

**Comment by oaksong** [comment]
지난 한해의 경험한 것들을 나누어주셔서 고맙습니다!
Pull request 를 통해 직접 기여해주시면 더 좋겠습니다 😀

**Comment by SambaLim** [comment]
2019 회고록 목록에 추가하고 pull request하였습니다.
감사합니다.😃

**Comment by oaksong** [comment]
#13
