### ISSUE TITLE
흔하지 않은, 좋은 웹 개발자가 되는 방법

### ISSUE THREAD

**Issue by kingbbode** [oaksong/developers-retrospective#2]
캡틴판교님께서 번역한 “흔하지 않은, 좋은 웹 개발자가 되는 방법(How to be an uncommonly good web developer)”이라는 미디엄 기사입니다.

7년의 경력을 가진 비전공 웹 개발자의 회고라고 보시면 됩니다. 최근에 강한 인상을 받았던 회고라 올라가있으면 하여 이슈로 남깁니다!

https://joshua1988.github.io/web-development/translation/how-to-become-uncommonly-web-dev/

좋은 프로젝트 만들어주셔서 감사합니다. :)

**Comment by oaksong** [comment]
소중한 회고 공유해주시고 공감해주셔서 고맙습니다.

올해도 함께 성장해가요!
